name: Tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2

    - name: Install micromamba
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba --strip-components=1
        else
          wget -qO- https://micromamba.snakepit.net/api/micromamba/osx-64/latest | tar -xvj bin/micromamba
          mv bin/micromamba ./micromamba
        fi
        ./micromamba shell init -s bash -p ~/micromamba
        mkdir -p ~/micromamba/pkgs/

    - name: Mamba install dependencies
      shell: bash -l {0}
      run: |
        export MAMBA_ROOT_PREFIX=~/micromamba
        export MAMBA_EXE=$(pwd)/micromamba
        . $MAMBA_ROOT_PREFIX/etc/profile.d/mamba.sh

        mamba install mamba python=${{ matrix.python-version }} "conda-build>=3.20" colorama pip ruamel ruamel.yaml rich pytest -c conda-forge

    - name: Install boa
      shell: bash -l {0}
      run: |
        export MAMBA_ROOT_PREFIX=~/micromamba
        export MAMBA_EXE=$(pwd)/micromamba
        . $MAMBA_ROOT_PREFIX/etc/profile.d/mamba.sh

        pip install .

    - name: Run tests
      shell: bash -l {0}
      run: |
        export MAMBA_ROOT_PREFIX=~/micromamba
        export MAMBA_EXE=$(pwd)/micromamba
        . $MAMBA_ROOT_PREFIX/etc/profile.d/mamba.sh

        pytest tests
